/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CreateHelpSeekerDto', 'model/HelpSeekerResource'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/CreateHelpSeekerDto'), require('../model/HelpSeekerResource'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.HelpSeekerRestServiceApi = factory(root.ApiDocumentation.ApiClient, root.ApiDocumentation.CreateHelpSeekerDto, root.ApiDocumentation.HelpSeekerResource);
  }
}(this, function(ApiClient, CreateHelpSeekerDto, HelpSeekerResource) {
  'use strict';

  /**
   * HelpSeekerRestService service.
   * @module api/HelpSeekerRestServiceApi
   * @version 1.0
   */

  /**
   * Constructs a new HelpSeekerRestServiceApi. 
   * @alias module:api/HelpSeekerRestServiceApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createHelpSeekerUsingPOST operation.
     * @callback module:api/HelpSeekerRestServiceApi~createHelpSeekerUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HelpSeekerResource} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * createHelpSeeker
     * @param {module:model/CreateHelpSeekerDto} helpSeeker helpSeeker
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.authenticated 
     * @param {String} opts.authorities0Authority 
     * @param {Object.<String, {String: String}>} opts.credentials 
     * @param {Object.<String, {String: String}>} opts.details 
     * @param {Object.<String, {String: String}>} opts.principal 
     * @param {module:api/HelpSeekerRestServiceApi~createHelpSeekerUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HelpSeekerResource}
     */
    this.createHelpSeekerUsingPOST = function(helpSeeker, opts, callback) {
      opts = opts || {};
      var postBody = helpSeeker;

      // verify the required parameter 'helpSeeker' is set
      if (helpSeeker === undefined || helpSeeker === null) {
        throw new Error("Missing the required parameter 'helpSeeker' when calling createHelpSeekerUsingPOST");
      }


      var pathParams = {
      };
      var queryParams = {
        'authenticated': opts['authenticated'],
        'authorities[0].authority': opts['authorities0Authority'],
        'credentials': opts['credentials'],
        'details': opts['details'],
        'principal': opts['principal'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = HelpSeekerResource;

      return this.apiClient.callApi(
        '/v1/help-seeker', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the searchHelpSeekerByPhoneUsingGET operation.
     * @callback module:api/HelpSeekerRestServiceApi~searchHelpSeekerByPhoneUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HelpSeekerResource} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * searchHelpSeekerByPhone
     * @param {String} phoneNumber phoneNumber
     * @param {module:api/HelpSeekerRestServiceApi~searchHelpSeekerByPhoneUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HelpSeekerResource}
     */
    this.searchHelpSeekerByPhoneUsingGET = function(phoneNumber, callback) {
      var postBody = null;

      // verify the required parameter 'phoneNumber' is set
      if (phoneNumber === undefined || phoneNumber === null) {
        throw new Error("Missing the required parameter 'phoneNumber' when calling searchHelpSeekerByPhoneUsingGET");
      }


      var pathParams = {
        'phoneNumber': phoneNumber
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = HelpSeekerResource;

      return this.apiClient.callApi(
        '/v1/help-seeker/search/{phoneNumber}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
