/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/LocationResource'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/LocationResource'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.LocationRestServiceApi = factory(root.ApiDocumentation.ApiClient, root.ApiDocumentation.LocationResource);
  }
}(this, function(ApiClient, LocationResource) {
  'use strict';

  /**
   * LocationRestService service.
   * @module api/LocationRestServiceApi
   * @version 1.0
   */

  /**
   * Constructs a new LocationRestServiceApi. 
   * @alias module:api/LocationRestServiceApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the geoCodeAddressUsingGET operation.
     * @callback module:api/LocationRestServiceApi~geoCodeAddressUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LocationResource} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * geoCodeAddress
     * @param {module:model/String} countryCode countryCode
     * @param {String} zipCode zipCode
     * @param {module:api/LocationRestServiceApi~geoCodeAddressUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LocationResource}
     */
    this.geoCodeAddressUsingGET = function(countryCode, zipCode, callback) {
      var postBody = null;

      // verify the required parameter 'countryCode' is set
      if (countryCode === undefined || countryCode === null) {
        throw new Error("Missing the required parameter 'countryCode' when calling geoCodeAddressUsingGET");
      }

      // verify the required parameter 'zipCode' is set
      if (zipCode === undefined || zipCode === null) {
        throw new Error("Missing the required parameter 'zipCode' when calling geoCodeAddressUsingGET");
      }


      var pathParams = {
      };
      var queryParams = {
        'countryCode': countryCode,
        'zipCode': zipCode,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = LocationResource;

      return this.apiClient.callApi(
        '/v1/location', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
