/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HelpSeekerResource', 'model/UserResource'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./HelpSeekerResource'), require('./UserResource'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.HelpRequestResource = factory(root.ApiDocumentation.ApiClient, root.ApiDocumentation.HelpSeekerResource, root.ApiDocumentation.UserResource);
  }
}(this, function(ApiClient, HelpSeekerResource, UserResource) {
  'use strict';

  /**
   * The HelpRequestResource model module.
   * @module model/HelpRequestResource
   * @version 1.0
   */

  /**
   * Constructs a new <code>HelpRequestResource</code>.
   * @alias module:model/HelpRequestResource
   * @class
   * @param adminUser {module:model/UserResource} 
   * @param createdAt {Date} 
   * @param helpSeeker {module:model/HelpSeekerResource} 
   * @param requestStatus {module:model/HelpRequestResource.RequestStatusEnum} 
   * @param requestText {String} 
   * @param updatedAt {Date} 
   */
  var exports = function(adminUser, createdAt, helpSeeker, requestStatus, requestText, updatedAt) {
    this.adminUser = adminUser;
    this.createdAt = createdAt;
    this.helpSeeker = helpSeeker;
    this.requestStatus = requestStatus;
    this.requestText = requestText;
    this.updatedAt = updatedAt;
  };

  /**
   * Constructs a <code>HelpRequestResource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HelpRequestResource} obj Optional instance to populate.
   * @return {module:model/HelpRequestResource} The populated <code>HelpRequestResource</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('adminUser'))
        obj.adminUser = UserResource.constructFromObject(data['adminUser']);
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('helpSeeker'))
        obj.helpSeeker = HelpSeekerResource.constructFromObject(data['helpSeeker']);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('requestStatus'))
        obj.requestStatus = ApiClient.convertToType(data['requestStatus'], 'String');
      if (data.hasOwnProperty('requestText'))
        obj.requestText = ApiClient.convertToType(data['requestText'], 'String');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
    }
    return obj;
  }

  /**
   * @member {module:model/UserResource} adminUser
   */
  exports.prototype.adminUser = undefined;

  /**
   * @member {Date} createdAt
   */
  exports.prototype.createdAt = undefined;

  /**
   * @member {module:model/HelpSeekerResource} helpSeeker
   */
  exports.prototype.helpSeeker = undefined;

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {module:model/HelpRequestResource.RequestStatusEnum} requestStatus
   */
  exports.prototype.requestStatus = undefined;

  /**
   * @member {String} requestText
   */
  exports.prototype.requestText = undefined;

  /**
   * @member {Date} updatedAt
   */
  exports.prototype.updatedAt = undefined;


  /**
   * Allowed values for the <code>requestStatus</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RequestStatusEnum = {
    /**
     * value: "CLOSED"
     * @const
     */
    CLOSED: "CLOSED",

    /**
     * value: "OPEN"
     * @const
     */
    OPEN: "OPEN",

    /**
     * value: "WIP"
     * @const
     */
    WIP: "WIP"
  };

  return exports;

}));
