/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OrderItemResource'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OrderItemResource'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.OrderResource = factory(root.ApiDocumentation.ApiClient, root.ApiDocumentation.OrderItemResource);
  }
}(this, function(ApiClient, OrderItemResource) {
  'use strict';

  /**
   * The OrderResource model module.
   * @module model/OrderResource
   * @version 1.0
   */

  /**
   * Constructs a new <code>OrderResource</code>.
   * @alias module:model/OrderResource
   * @class
   * @param createdAt {Date} 
   * @param items {Array.<module:model/OrderItemResource>} 
   * @param source {module:model/OrderResource.SourceEnum} 
   * @param status {module:model/OrderResource.StatusEnum} 
   * @param updatedAt {Date} 
   */
  var exports = function(createdAt, items, source, status, updatedAt) {
    this.createdAt = createdAt;
    this.items = items;
    this.source = source;
    this.status = status;
    this.updatedAt = updatedAt;
  };

  /**
   * Constructs a <code>OrderResource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderResource} obj Optional instance to populate.
   * @return {module:model/OrderResource} The populated <code>OrderResource</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('hint'))
        obj.hint = ApiClient.convertToType(data['hint'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('items'))
        obj.items = ApiClient.convertToType(data['items'], [OrderItemResource]);
      if (data.hasOwnProperty('maxPrice'))
        obj.maxPrice = ApiClient.convertToType(data['maxPrice'], 'Number');
      if (data.hasOwnProperty('source'))
        obj.source = ApiClient.convertToType(data['source'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
    }
    return obj;
  }

  /**
   * @member {Date} createdAt
   */
  exports.prototype.createdAt = undefined;

  /**
   * @member {String} hint
   */
  exports.prototype.hint = undefined;

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {Array.<module:model/OrderItemResource>} items
   */
  exports.prototype.items = undefined;

  /**
   * @member {Number} maxPrice
   */
  exports.prototype.maxPrice = undefined;

  /**
   * @member {module:model/OrderResource.SourceEnum} source
   */
  exports.prototype.source = undefined;

  /**
   * @member {module:model/OrderResource.StatusEnum} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {Date} updatedAt
   */
  exports.prototype.updatedAt = undefined;


  /**
   * Allowed values for the <code>source</code> property.
   * @enum {String}
   * @readonly
   */
  exports.SourceEnum = {
    /**
     * value: "ADMIN"
     * @const
     */
    ADMIN: "ADMIN",

    /**
     * value: "APP"
     * @const
     */
    APP: "APP",

    /**
     * value: "HOTLINE"
     * @const
     */
    HOTLINE: "HOTLINE"
  };


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "ACCEPTED"
     * @const
     */
    ACCEPTED: "ACCEPTED",

    /**
     * value: "CONSUMER_CANCELLED"
     * @const
     */
    CONSUMER_CANCELLED: "CONSUMER_CANCELLED",

    /**
     * value: "DELIVERED"
     * @const
     */
    DELIVERED: "DELIVERED",

    /**
     * value: "TO_BE_DELIVERED"
     * @const
     */
    TO_BE_DELIVERED: "TO_BE_DELIVERED"
  };

  return exports;

}));
