/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/UpdateHelpSeekerDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./UpdateHelpSeekerDto'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.UpdateHelpRequestContentDto = factory(root.ApiDocumentation.ApiClient, root.ApiDocumentation.UpdateHelpSeekerDto);
  }
}(this, function(ApiClient, UpdateHelpSeekerDto) {
  'use strict';

  /**
   * The UpdateHelpRequestContentDto model module.
   * @module model/UpdateHelpRequestContentDto
   * @version 1.0
   */

  /**
   * Constructs a new <code>UpdateHelpRequestContentDto</code>.
   * @alias module:model/UpdateHelpRequestContentDto
   * @class
   * @param helpSeeker {module:model/UpdateHelpSeekerDto} 
   * @param requestText {String} 
   */
  var exports = function(helpSeeker, requestText) {
    this.helpSeeker = helpSeeker;
    this.requestText = requestText;
  };

  /**
   * Constructs a <code>UpdateHelpRequestContentDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateHelpRequestContentDto} obj Optional instance to populate.
   * @return {module:model/UpdateHelpRequestContentDto} The populated <code>UpdateHelpRequestContentDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('helpSeeker'))
        obj.helpSeeker = UpdateHelpSeekerDto.constructFromObject(data['helpSeeker']);
      if (data.hasOwnProperty('requestText'))
        obj.requestText = ApiClient.convertToType(data['requestText'], 'String');
    }
    return obj;
  }

  /**
   * @member {module:model/UpdateHelpSeekerDto} helpSeeker
   */
  exports.prototype.helpSeeker = undefined;

  /**
   * @member {String} requestText
   */
  exports.prototype.requestText = undefined;

  return exports;

}));
