/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.UpdateHelpRequestStatusDto = factory(root.ApiDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The UpdateHelpRequestStatusDto model module.
   * @module model/UpdateHelpRequestStatusDto
   * @version 1.0
   */

  /**
   * Constructs a new <code>UpdateHelpRequestStatusDto</code>.
   * @alias module:model/UpdateHelpRequestStatusDto
   * @class
   * @param status {module:model/UpdateHelpRequestStatusDto.StatusEnum} 
   */
  var exports = function(status) {
    this.status = status;
  };

  /**
   * Constructs a <code>UpdateHelpRequestStatusDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateHelpRequestStatusDto} obj Optional instance to populate.
   * @return {module:model/UpdateHelpRequestStatusDto} The populated <code>UpdateHelpRequestStatusDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
    }
    return obj;
  }

  /**
   * @member {module:model/UpdateHelpRequestStatusDto.StatusEnum} status
   */
  exports.prototype.status = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "CLOSED"
     * @const
     */
    CLOSED: "CLOSED",

    /**
     * value: "OPEN"
     * @const
     */
    OPEN: "OPEN",

    /**
     * value: "WIP"
     * @const
     */
    WIP: "WIP"
  };

  return exports;

}));
