/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OrderResource', 'model/UserResource'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OrderResource'), require('./UserResource'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.UserOrderResponse = factory(root.ApiDocumentation.ApiClient, root.ApiDocumentation.OrderResource, root.ApiDocumentation.UserResource);
  }
}(this, function(ApiClient, OrderResource, UserResource) {
  'use strict';

  /**
   * The UserOrderResponse model module.
   * @module model/UserOrderResponse
   * @version 1.0
   */

  /**
   * Constructs a new <code>UserOrderResponse</code>.
   * @alias module:model/UserOrderResponse
   * @class
   * @param order {module:model/OrderResource} 
   */
  var exports = function(order) {
    this.order = order;
  };

  /**
   * Constructs a <code>UserOrderResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserOrderResponse} obj Optional instance to populate.
   * @return {module:model/UserOrderResponse} The populated <code>UserOrderResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('driver'))
        obj.driver = UserResource.constructFromObject(data['driver']);
      if (data.hasOwnProperty('order'))
        obj.order = OrderResource.constructFromObject(data['order']);
    }
    return obj;
  }

  /**
   * @member {module:model/UserResource} driver
   */
  exports.prototype.driver = undefined;

  /**
   * @member {module:model/OrderResource} order
   */
  exports.prototype.order = undefined;

  return exports;

}));
